
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: controlplane1, address: 172.237.5.151, internalAddress: 172.237.5.151, user: root, password: "xup6jo3fup6"}
  - {name: node1, address: 139.162.91.214, internalAddress: 139.162.91.214, user: root, password: "xup6jo3fup6"}
  - {name: node2, address: 172.105.209.143, internalAddress: 172.105.209.143, user: root, password: "xup6jo3fup6"}
  roleGroups:
    etcd:
    - controlplane1
    control-plane: 
    - controlplane1
    worker:
    - node1
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.30.6
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []


