version: "2"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true                      # 啟用授權
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity      # 身份密鑰
      - NACOS_AUTH_IDENTITY_VALUE=security           # 身份值
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789 # 安全金鑰
      - NACOS_SERVER_IP=127.0.0.1                   # 指定 Nacos 伺服器 IP
      - NACOS_SERVER_PORT=8848                       # Nacos 伺服器端口
      - NACOS_USER=nacos                             # 設定默認用戶名
      - NACOS_PASSWORD=nacos                         # 設定默認密碼
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure
