apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demo-basic-services  # 使用正确的命名空间
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP  # Service 类型为 ClusterIP
