apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data  # 在您的主机上创建一个目录，例如 /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-basic-services  # 使用正确的命名空间
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

